#!/bin/bash

echo "$1"

aws configure set aws_access_key_id $(cat "$1" | awk -F , 'NR % 2 == 0{print $1}')
aws configure set aws_secret_access_key $(cat "$1" | awk -F , 'NR % 2 == 0{print $2}')
aws configure set default.region us-west-2
srm "$1"

